# Generated by Django 4.2 on 2023-05-03 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FABLAB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='Prerequis',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='quantite',
        ),
    ]
