# Generated by Django 4.2 on 2023-05-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FABLAB', '0002_remove_machine_prerequis_remove_machine_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='quantite',
            field=models.IntegerField(blank=True, null=True, verbose_name='quantite'),
        ),
    ]
