# Generated by Django 4.2 on 2023-05-03 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FABLAB', '0003_machine_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='Prerequis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FABLAB.trainingcategory'),
        ),
    ]
