# Generated by Django 4.2 on 2023-05-03 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FABLAB', '0004_machine_prerequis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='Prerequis',
        ),
    ]
