# Generated by Django 4.2 on 2023-05-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FABLAB', '0005_remove_machine_prerequis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trustpilot',
            new_name='Testimonial',
        ),
    ]
