# Generated by Django 4.2 on 2023-05-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FABLAB', '0006_rename_trustpilot_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.FileField(default=1, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='profession',
            field=models.CharField(default=2, max_length=255, verbose_name='Profession'),
            preserve_default=False,
        ),
    ]
