# Generated by Django 4.2 on 2023-05-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FABLAB', '0007_testimonial_image_testimonial_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parteneire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('link', models.CharField(max_length=255, unique=True, verbose_name='lien')),
                ('image', models.ImageField(upload_to='media')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.DeleteModel(
            name='Galery',
        ),
    ]
